apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
  - image: mysql
    name: mysql-pod
    envFrom:
    - configMapRef:
       name: db-config
    - secretRef:
       name: db-secret
    resources:
      requests:
        ephemeral-storage: 4Gi
      limits:
        ephemeral-storage: 6Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
