apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: php
  name: phpapp-svc
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 80
  selector:
    run: php
  type: NodePort
status:
  loadBalancer: {}
