apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: phpadmin-pod
  name: phpadmin-pod
spec:
  containers:
  - image: phpmyadmin
    name: phpadmin-pod
    envFrom:
    - configMapRef:
       name: phpadmin-config
    - secretRef:
       name: phpadmin-secret
    resources:
      requests:
        ephemeral-storage: 2Gi
      limits:
        ephemeral-storage: 3Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
